{{ if (eq (include "performDeployment" .) "true") }}
# Only attempt to generate this file IF the user has NOT supplied
# an external search URL or enabled the search service, which means we
# need to deploy Elasticsearch internally.
{{ if (eq (include "isExternalSearch" .) "true") }} {{ else }}
kind: Service
apiVersion: v1
metadata:
  name: {{ template "searchName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: Pega
    app: {{ template "searchName" . }}
spec:
  selector:
    component: Search
    app: {{ template "searchName" . }}
  ports:
  - name: http
    port: 80
    targetPort: 9200
{{ end }}
{{ end }}